[package]
name = "statuses-rs"
version = "1.0.0"
edition = "2021"

[dependencies]
networkmanager = "0.4.1"
dbus = "0.9.7"
nix = { version = "0.29.0", features = ["net", "socket"] }

[profile.release]
opt-level = 3
